language: ruby
rvm:
  - 2.1
  - 2.0
sudo: false
cache: bundler
gemfile:
  - gemfiles/gemfile.rails4
  - gemfiles/gemfile.rails4.1
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

notifications:
  irc: "irc.freenode.org#projecthydra"
